apiVersion: v1
kind: Secret
metadata:
  name: repo-thomassuedbroecker-iascable-gitops.git
  namespace: openshift-gitops
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/argoproj/private-repo
